pipeline {
    environment {
        registry = "khaledsd/garkclub_frontend"
        registryCredential = 'docker2'
        dockerImage = ''
    }
    agent any
    stages {
       stage('Build') {
            steps {
                script {
                   dockerImage = docker.build registry + ":$BUILD_NUMBER"
                }
            }
        }
        stage('Push') {
            steps {
                script {
                    docker.withRegistry( '', registryCredential ) {
                                            dockerImage.push()
                                        }
                }
            }
        }

        stage('Trigger PipelineJob2') {
            steps {
                script {
                        build job: 'CD pipe/main', wait: false
                }
            }
        }
      /*    stage('Run') {
            steps {
                script {
                    dockerImage.run("-p 4250:4200 ")
                }
            }
        }
    stage('SSH Connection') {

            steps {
                script {
                     def remote = [:]
                    remote.name = 'server-kali'
                    remote.host = '192.168.56.103'
                    remote.user = 'kali'
                    remote.password = 'kali'
                    remote.allowAnyHosts = true
                    sshCommand remote: remote, command: 'bash deploy.sh'

                }
            }
        }*/


    }
}


