name: SSH Deployment
on:
  workflow_dispatch: # Manually trigger workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install sshpass
      run: sudo apt-get install -y sshpass 
    - name: SSH into VPS and update code front
      run: sudo sshpass -p ${{secrets.PASSWORD}} ssh -i ~/.ssh/id_rsa -vvv -o StrictHostKeyChecking=no ubuntu@5.196.15.147 "cd GarkAcademy/GarkAcademy2024-Admin && sudo git pull https://khaledsaadouni:${{secrets.TOKEN}}@github.com/Gark-Academy/GarkAcademy2024-Admin production  " 
    - name: SSH into VPS and update code back
      run: sudo sshpass -p ${{secrets.PASSWORD}} ssh -i ~/.ssh/id_rsa -vvv -o StrictHostKeyChecking=no ubuntu@5.196.15.147 "cd GarkAcademy/GarkAcademy2024-Back && sudo git pull https://khaledsaadouni:${{secrets.TOKEN}}@github.com/Gark-Academy/GarkAcademy2024-Back production  " 
    - name: build and run 
      run: sudo sshpass -p ${{secrets.PASSWORD}} ssh -i ~/.ssh/id_rsa -vvv -o StrictHostKeyChecking=no ubuntu@5.196.15.147 "cd GarkAcademy && sudo docker compose down && sudo docker compose up -d --build "
      
    
