name: SSH Deployment
on:
  workflow_dispatch: # Manually trigger workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install sshpass
      run: sudo apt-get install -y sshpass
    - name: ssh
      run: sudo sshpass -p '${{secrets.VPS_PASS}}' ssh -o "StrictHostKeyChecking no" 5.196.15.147 "whoami"
    - name: SSH into VPS and update code
      run:  sshpass -p '${{secrets.VPS_PASS}}'  ssh -i ~/.ssh/id_rsa -vvv -o StrictHostKeyChecking=no ubuntu@5.196.15.147 "mkdir test && ls"
      
    
