name: SSH Deployment
on:
  workflow_dispatch: # Manually trigger workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install sshpass
      run: sudo apt-get install -y sshpass 
    - name: SSH into VPS and update code
      run: sudo sshpass -p ${{secrets.PASSWORD}}  ssh -i ~/.ssh/id_rsa -vvv -o StrictHostKeyChecking=no root@5.196.15.147 "ls  "
      
    
